module.exports = {
    moduleFileExtensions: ['js', 'json', 'ts'],
    rootDir: 'src',
    testRegex: '.*\\.spec\\.ts$',
    transform: {
        '^.+\\.(t|j)s$': 'ts-jest',
    },
    collectCoverageFrom: [
        '**/*.(t|j)s',
        '!**/*.module.ts',
        '!**/*.model.ts',
        '!**/index.ts',
        '!**/main.ts',
        '!./shared/middleware/**',
        '!./shared/infra/logger/**',
        '!./tracing.ts',
        '!**/*.exception.ts',
        '!**/*.controller.ts',
        '!**/*.dto.ts',
        '!**/*.repository.ts',
        '!**/domain/services/**',
        '!**/tracing.ts',
        '!**/logger/**',
        '!**/middleware/**',
    ],
    coverageDirectory: '../coverage',
    coverageReporters: ['lcov', 'text', 'json'],
    testEnvironment: 'node',
};
