name: Dev workflow

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  CI:
    uses: ./.github/workflows/test.yml
    with:
      test_threshold: 80
    
  CD:
    uses: ./.github/workflows/deploy.yml
    needs: CI
    with:
      environment: dev
      aws_region: "us-east-1"
      aws_role_to_assume: "arn:aws:iam::593755927326:role/GitHub_Actions"
      aws_s3_state_bucket: "terraform-remote-state-ci-backend"